name: Execução dos testes regressivos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get Code
        uses: actions/checkout@v3.5.3
      
      - name: install dependencies
        run: npm install
        
      - name: Run Regressives Tests
        run: npx cypress run
    
